"""Plot all trajectory data (generated by optimization algorithm, measured in
simulation, and measured on hardware)

"""

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import argparse
import numpy as np


def plot_state_traj(path_collocation_state_traj: Path,
                    path_sample_state_traj: Path,
                    path_state_bounds_traj: Path,
                    algorithm_name: str):
    """Plot joint state trajectories."""
    # read data
    df_coll_state_traj = pd.read_csv(path_collocation_state_traj)
    df_sample_state_traj = pd.read_csv(path_sample_state_traj)
    df_state_bounds_traj = pd.read_csv(path_state_bounds_traj)

    # Each state trajectory row is: [time, q, dq, ddq] where q, dq, and ddq are
    # row vectors, each with as many elements as there are joints. Each state
    # bounds trajectory row is [time, x0_low, x0_high, ..., x(n-1)_low,
    # x(n-1)_high], where n is the state length.
    
    num_joints = int((len(df_coll_state_traj.columns) - 1) / 3)
    
    fig_ax_tuples = []
    joint_label = ["q", "dq", "ddq"]
    joint_title_names = ["Position", "Velocity", "Acceleration"]
    for i in range(len(joint_label)):
        fig, ax = plt.subplots()
        for j in range(num_joints):
            # plot collocation points
            line, = ax.plot(df_coll_state_traj.time, df_coll_state_traj.iloc[:, i*num_joints + j + 1], 'o', label="{}[{}]".format(joint_label[i], j))
            # plot sample trajectory
            ax.plot(df_sample_state_traj.time, df_sample_state_traj.iloc[:, i*num_joints + j + 1], color=line.get_color())

            # state bounds only apply to position and velocity so skip
            # acceleration
            if i >= 2:
                continue

            # Only plot the path bounds once (same for every joint)
            if j != num_joints-1:
                continue

            inf = 1e6
            col_low = "x{}_low".format(i*num_joints + j)
            df_low = df_state_bounds_traj[["time", col_low]]
            # exclude start and end bounds
            df_low = df_low.iloc[1:-1,:]
            # remove large values in magnitude
            df_low = df_low[df_low[col_low] >= -inf]

            col_high = "x{}_high".format(i*num_joints + j)
            df_high = df_state_bounds_traj[["time", col_high]]
            # exclude start and end bounds
            df_high = df_high.iloc[1:-1,:]
            # remove large values in magnitude
            df_high = df_high[df_high[col_high] <= inf]

            # plot bounds
            if not df_low.empty:
                ax.plot(df_low.time, df_low.iloc[:, 1], 'D', label="min.".format(joint_label[i], j))
            if not df_high.empty:
                ax.plot(df_high.time, df_high.iloc[:, 1], 'D', label="max.".format(joint_label[i], j))

        ax.set_title(f"Target {algorithm_name} Collocation Joint {joint_title_names[i]} Trajectory")
        ax.set_xlabel("time [s]")
        ax.grid(True)
        ax.legend()
        fig_ax_tuples.append((fig, ax))
    return fig_ax_tuples
    

def calc_err_traj(target_state_traj, true_state_traj):
    """Calculate the error between the target and actual state
    trajectories. Each error is calculated for a target trajectory time point,
    linearly interpolating the actual trajectory value at that time.

    """
    
    err_traj = np.zeros_like(target_state_traj)

    it_true = zip(true_state_traj, true_state_traj[1:])
    true_left, true_right = next(it_true)
    for i, target in enumerate(target_state_traj):
        # find true interval that overlaps with target time
        while target[0] > true_right[0]:
            true_left, true_right = next(it_true)
        # linearly interpolate true state value at target time
        alpha = (target[0] - true_left[0])/(true_right[0] - true_left[0])
        true_est = alpha*(true_right - true_left) + true_left
        # calculate error = target - true
        error = target - true_est
        # set the time to the target time
        error[0] = target[0]
        # save error
        err_traj[i] = error
    return err_traj


def plot_state_traj_sim_err(path_sample_state_traj: Path,
                            path_sim_state_traj: Path,
                            algorithm_name: str):
    """Plot the joint state trajectory errors between the target trajectory and
    the actual simulated trajectory."""
    # read data
    sample_state_traj = pd.read_csv(path_sample_state_traj).to_numpy()
    sim_state_traj = pd.read_csv(path_sim_state_traj).to_numpy()
    
    state_err_traj = calc_err_traj(target_state_traj=sample_state_traj,
                                   true_state_traj=sim_state_traj)
    
    # each row is: [time, q, dq, ddq] where q, dq, and ddq are row vectors, each
    # with as many elements as there are joints
    
    num_joints = int((state_err_traj.shape[1] - 1) / 3)
    
    fig_ax_tuples = []
    joint_label = ["q", "dq", "ddq"]
    joint_title_names = ["Position Error", "Velocity Error", "Acceleration Error"]
    for i in range(len(joint_label)):
        fig, ax = plt.subplots()
        for j in range(num_joints):
            ax.plot(state_err_traj[:,0], state_err_traj[:, i*num_joints + j + 1], label=" {}[{}]".format(joint_label[i], j))

        ax.set_title(f"{algorithm_name} Collocation Joint {joint_title_names[i]} Trajectory")
        ax.set_xlabel("time [s]")
        ax.grid(True)
        ax.legend()
        fig_ax_tuples.append((fig, ax))
    return fig_ax_tuples


def plot_ctrl_traj(path_collocation_ctrl_traj,
                   path_sample_ctrl_traj,
                   algorithm_name):
    df_coll_ctrl_traj = pd.read_csv(path_collocation_ctrl_traj)
    df_sample_ctrl_traj = pd.read_csv(path_sample_ctrl_traj)

    # each row is: [time, u] where u is a row vector with as many elements as
    # there are control input elements (no more than the number of joints)
    num_ctrls = len(df_coll_ctrl_traj.columns) - 1
    
    fig, ax = plt.subplots()
    for i in range(num_ctrls):
        line, = ax.plot(df_coll_ctrl_traj.time, df_coll_ctrl_traj.iloc[:, i+1], 'o', label="u[{}]".format(i))
        ax.plot(df_sample_ctrl_traj.time, df_sample_ctrl_traj.iloc[:, i+1], color=line.get_color())
    ax.set_title(f"{algorithm_name} Collocation Joint Control Trajectory")
    ax.set_xlabel("time [s]")
    ax.grid(True)
    ax.legend()
    return (fig, ax)


def main():
    # parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument("--traj-data-dir", help="Path to directory containing trajectory data files.", type=Path, required=True)
    parser.add_argument("--algorithm", help="Type of algorithm.", type=str, choices=["Trapezoidal", "Hermite-Simpson"], default="Trapezoidal")
    parser.add_argument("--model", help="Type of model.", type=str, choices=["cartpole", "so101"], default="Trapezoidal")
    args = parser.parse_args()

    # construct file names
    algs_lower = args.algorithm.lower()
    filename_collocation_state_traj = f"collocation-state-traj-{algs_lower}-{args.model}.csv"
    filename_collocation_ctrl_traj = f"collocation-ctrl-traj-{algs_lower}-{args.model}.csv"
    filename_sample_state_traj = f"sample-state-traj-{algs_lower}-{args.model}.csv"
    filename_sample_ctrl_traj = f"sample-ctrl-traj-{algs_lower}-{args.model}.csv"
    filename_col_state_bounds_traj = f"state-traj-bounds-{algs_lower}-{args.model}.csv"
    filename_col_ctrl_bounds_traj = f"ctrl-traj-bounds-{algs_lower}-{args.model}.csv"
    filename_sim_state_traj = "sim-state-traj.csv"

    # plots

    fig_ax_tuples = plot_state_traj(
        path_collocation_state_traj=args.traj_data_dir / filename_collocation_state_traj,
        path_sample_state_traj=args.traj_data_dir / filename_sample_state_traj,
        path_state_bounds_traj=args.traj_data_dir / filename_col_state_bounds_traj,
        algorithm_name=args.algorithm
    )

    # fig_ax_tuples += plot_state_traj_sim_err(
    #     path_sample_state_traj=args.traj_data_dir / filename_sample_state_traj,
    #     path_sim_state_traj = args.traj_data_dir / filename_sim_state_traj,
    #     algorithm_name=args.algorithm
    # )
    
    # fig_ax_tuples += plot_ctrl_traj(
    #     path_collocation_ctrl_traj=args.traj_data_dir / filename_collocation_ctrl_traj,
    #     path_sample_ctrl_traj=args.traj_data_dir / filename_sample_ctrl_traj,
    #     algorithm_name=args.algorithm
    # )
    
    plt.show()


if __name__ == "__main__":    
    main()
